import { useState } from "react";
import { useAdminUserAction, useAdminUsers } from "../../entities/admin/api";
import { errorMessage } from "../../shared/api/client";

export function AdminUserPanel() {
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [reason, setReason] = useState("Policy violation");
  const users = useAdminUsers({ search, status });
  const action = useAdminUserAction();
  const [feedback, setFeedback] = useState<string | null>(null);

  return <section aria-labelledby="user-controls-heading" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">Account controls</p><h2 id="user-controls-heading" className="mt-1 text-lg font-semibold text-slate-950">Users</h2><p className="mt-1 text-sm text-slate-500">Review account status and immediately revoke sessions when banning a user. Passwords and secret fields are never shown.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">Admin only</span></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, email, or user ID" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-indigo-200" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700"><option value="">All statuses</option><option value="active">Active</option><option value="banned">Banned</option></select><input value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Ban reason" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-indigo-200" /></div>
    {feedback && <p role="status" className="mt-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{feedback}</p>}
    <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="border-b border-slate-100 text-slate-400"><tr><th className="pb-2 font-medium">Account</th><th className="pb-2 font-medium">Status</th><th className="pb-2 font-medium">Created</th><th className="pb-2 font-medium">Ban reason</th><th className="pb-2 text-right font-medium">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{(users.data ?? []).map((user) => <tr key={user.id}><td className="py-3"><p className="font-medium text-slate-800">{user.name} {user.is_admin ? <span className="ml-1 rounded bg-indigo-50 px-1.5 py-0.5 text-[10px] text-indigo-700">admin</span> : null}</p><p className="text-slate-500">{user.email} · {user.id}</p></td><td className="py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${user.account_status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{user.account_status}</span></td><td className="py-3 text-slate-500">{new Date(user.created_at).toLocaleDateString()}</td><td className="max-w-[220px] truncate py-3 text-slate-500">{user.ban_reason || "—"}</td><td className="py-3 text-right">{user.is_admin ? <span className="text-slate-400">Protected admin</span> : <button type="button" disabled={action.isPending} onClick={() => action.mutate({ id: user.id, action: user.account_status === "active" ? "ban" : "unban", reason }, { onSuccess: () => setFeedback(`${user.email} ${user.account_status === "active" ? "banned" : "unbanned"}.`), onError: (error) => setFeedback(errorMessage(error)) })} className={`font-semibold ${user.account_status === "active" ? "text-rose-600 hover:text-rose-800" : "text-emerald-600 hover:text-emerald-800"}`}>{user.account_status === "active" ? "Ban user" : "Unban user"}</button>}</td></tr>)}</tbody></table>{users.isLoading && <p className="py-6 text-center text-sm text-slate-400">Loading users…</p>}{!users.isLoading && users.data?.length === 0 && <p className="py-6 text-center text-sm text-slate-400">No users match this filter.</p>}</div>
  </section>;
}
